server:
  port: 8080
spring:
  datasource:
    url:  jdbc:h2:mem:recipe
    driverClassName: org.h2.Driver
    username: user
    password: password
    data: classpath:data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:schema.sql

  h2:
   console:
     enabled: true

entityManager:
  packagesToScan: com.recipe
